// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Start() {
  return window['go']['core']['App']['Start']();
}

export function Stop() {
  return window['go']['core']['App']['Stop']();
}
